# Site
name: "Security Token Accelerator Blog"
description: "Security Token Accelerator Blog"
meta_description: "Security Token Accelerator Blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /blog
google_analytics: ''
disqus: ''
mailchimp-list: ''

# Authors
authors:
  xenia:
    name: Xenia
    display_name: Xenia
    gravatar: 
    email: 
    web: 
    twitter: 
    description: "Author of STA Blog"
  
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge